mongo: ${MONGO_URL|mongodb://localhost/mylife-money}
webServer:
  address: :${WEB_PORT|80}
secrets:
  path: ${SECRETS_PATH}
bots:
  cic-scraper:
    user: secret:cic-user
    pass: secret:cic-pass
    account: common
mail-sender:
  smtp-server: smtp.gmail.com
  smtp-port: 587
  user: secret:mail-sender-user
  pass: secret:mail-sender-pass
  from: secret:mail-sender-from
  to: secret:mail-sender-to