mongo: ${MONGO_URL|mongodb://localhost/mylife-money}
webServer:
  address: :${WEB_PORT|80}
secrets:
  path: ${SECRETS_PATH}
bots:
  cic-scraper:
    user: secret:cic-user
    pass: secret:cic-pass
    account: common