mongo: ${MONGO_URL|mongodb://localhost/mylife-energy}
bus:
  serverUrl: ${BUS_SERVER|tcp://rpi-dev-home-main}
webServer:
  address: :${WEB_PORT|80}
tesla:
  id: ${TESLA_ID}
  tokenPath: ${TESLA_TOKEN|/tesla.token}
  wallConnectorAddress: ${TWC_ADDRESS}