mongo: ${MONGO_URL|mongodb://localhost/mylife-energy}
bus:
  serverUrl: ${BUS_SERVER|tcp://rpi-dev-home-main}
webServer:
  address: :${WEB_PORT|80}
tesla:
  id: ${TESLA_ID}
  vin: ${TESLA_VIN}
  # Must contain fleet-api.token, owner-api.token, vehicle-private-key.pem
  fleetClientId: ${TESLA_FLEET_CLIENT_ID}
  authPath: ${TESLA_AUTH_PATH|~/}
  wallConnectorAddress: ${TWC_ADDRESS}