mongo: ${MONGO_URL|mongodb://localhost/mylife-energy}
bus:
  serverUrl: ${BUS_SERVER|tcp://rpi-dev-home-main}
webServer:
  address: :${WEB_PORT|80}
monitor:
  address: :${MONITOR_PORT|81}
tesla:
  id: ${TESLA_ID}
  vin: ${TESLA_VIN}
  # Must contain (fleet-api.token), owner-api.token, vehicle-private-key.pem
  authPath: ${TESLA_AUTH_PATH|~/}
  # fleetClientId: ${TESLA_FLEET_CLIENT_ID}
  bleProxy: ${TESLA_BLE_PROXY}
  wallConnectorAddress: ${TWC_ADDRESS}